version: '3'
services:
  mongo:
    container_name: mongo_user_db
    image: mongo
    ports:
      - "27019:27017"
  app:
    container_name: user_service
    restart: always
    build: .
    env_file: .env
    ports:
      - "4002:4000"
    links:
      - mongo
