apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: auth-mongo-db
  name: auth-mongo-db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: auth-mongo-db
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.1 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: auth-mongo-db
    spec:
      containers:
        - image: mongo
          name: auth-mongo-db
          ports:
            - containerPort: 27017
          resources: {}
      restartPolicy: Always
status: {}
