version: '3'
services:
  auth-mongo-db:
    container_name: auth-mongo-db
    image: mongo
    ports:
      - "27018:27017"
  auth-backend:
    container_name: auth-backend
    restart: always
    build: .
    env_file: .env
    ports:
      - "4001:4000"
    links:
      - mongo
